nim secret (Fix to work again)
nim-works/nimskull pull request #1035
Opened 2023-11-29 23:22 UTC by nixfreak

When running `nim secret` the default compiler is backendC and should be backendVm.

## Summary
* what changed and how?
Added logic to compilation environment to disable ```backendC``` when calling ```nim secret``` and instead change to ```backendVm```
* why are we changing it? 

> Okay, the root of the problem is that the compilation environment is configured for as if the C backend were used. This leads to various semantic errors, and while that still shouldn't crash the compiler, it unfortunately does. Anyhow, since the REPL is effectively a backend itself, the customizeForBackend call at main.nim:510 needs to be disabled when the REPL is used (indicated bycmdInteractive).
commandInteractive (the procedure setting up the REPL) then needs to call customizeForBackend itself, but with backendVm rather than backendC.

## Details
* Credit goes to @zerbina:matrix.org

---

## Notes for Reviewers
* leave additional context for reviewers
* maybe specific requests or areas of focus

<!--
Pull Request(PR) Help

Before Merge Ensure:
* title reads like a short changelog line entry
* code includes tests and is documented
* leave the source better than before, but split out big reformats

See contributor (guide)[https://nim-works.github.io/nimskull/contributing.html]
for details, especially if you're new to this project.

Tips that make PRs easier:
* for big/impactful changes, start with chat/discussions to refine ideas
* refine the pull request message over time; don't have to nail it in one go

2023-11-30 00:27 UTC, zerbina requested changes
Thank you for creating the PR, having `nim secret` operational again makes quickly trying out some code much easier. I left a suggestion for fixing the typo with procedure name.

So that future regression don't go by unnoticed, could you add a basic test for the REPL? The test (e.g., `trepl.nim`) should go into the `tests/compiler` directory and do the following:
* invoke the compiler with the `secret` command
* ensure that the three arrows appear without any errors
* send an `echo ...` statement to the process
* verify that the echoed string appears in the process' output
* send a `quit()` statement to the process
* verify that the process terminates

This ensures that the REPL starts and can be shutdown again.

---

Both the title and PR body need some adjustments:
* since it's a user-facing bugfix, the title should broadly summarize what the fix does (e.g., "make the `nim secret` command work again")
* what's currently in the Summary section should be part of the Details section, and the quote should be shortened a bit
* finally, the Summary section then summarizes the Details section, which in the case of this PR could be a slightly more detailed version of the title I suggested

If okay with you, I can also update both the title and PR body to be in line with
the general PR style.

2023-11-30 00:27 UTC, zerbina commented on compiler/front/main.nim
> +    customizeForBackened(graph, conf, backendNimVm)
```suggestion
    customizeForBackend(graph, conf, backendNimVm)
```

2023-12-05 19:26 UTC, nixfreak commented
Looking into how to test nim secret via nim files.

2024-05-13 20:55 UTC, zerbina commented
@nixfreak: How's the progress on this PR?

2024-06-18 20:12 UTC, zerbina commented
Superseded by #1351.

2024-06-18 20:12 UTC, closed without merging