Add style_guide.html to intern.rst
nim-works/nimskull pull request #1050
Opened 2023-12-06 05:11 UTC by nixfreak

## Summary
* Intern.rst has a link to old nep1.html style guide. Replaced nep1.html with  style_guide.html.
* The link does not exist

## Details
* info that couldn't fit into the summary
* relevant details; tricky parts
* anything else

Fixes full_issue_url

---

## Notes for Reviewers
* leave additional context for reviewers
* maybe specific requests or areas of focus

<!--
Pull Request(PR) Help

Before Merge Ensure:
* title reads like a short changelog line entry
* code includes tests and is documented
* leave the source better than before, but split out big reformats

See contributor (guide)[https://nim-works.github.io/nimskull/contributing.html]
for details, especially if you're new to this project.

Tips that make PRs easier:
* for big/impactful changes, start with chat/discussions to refine ideas
* refine the pull request message over time; don't have to nail it in one go

2023-12-06 15:43 UTC, zerbina requested changes
Thank you for fixing documentation issues. The documentation generator doesn't check for stale links or anchors at the moment (but it really should), so it's easy for links to start pointing to non-existent documents.

The title is good, but the PR message needs to not contain parts of the message template.

Also, for improved readability, could you wrap the names of the files within the PR message and title in backward quotes? That'll make them appear like `this`, which is slightly easier to read. Thanks.

2023-12-06 15:43 UTC, zerbina commented on readme.md
> +./koch.py docs -d: release
```suggestion
```
An unrelated change part of the other PR.

2024-03-13 10:32 UTC, Clyybber commented on readme.md
> +./koch.py docs -d: release
Commited the suggestion now, since "Maintainers are allowed to edit this pull request." is enabled on this PR.

2024-03-13 11:11 UTC, Clyybber commented
/merge

2024-03-13 15:59 UTC, zerbina approved these changes

2024-03-13 16:44 UTC, merged