doc: 'PRs are welcome' reply recommendations
nim-works/nimskull pull request #132
Opened 2021-12-27 14:24 UTC by haxscramper

Elaborate on how "PRs are welcome" replies should be used.

2021-12-27 15:45 UTC, Vindaar commented on doc/moderation.rst
> +seem dismissive and counterproductive - instead of telling person asking for a
```suggestion
seem dismissive and counterproductive - instead of telling the person asking for a
```

2021-12-27 15:45 UTC, Vindaar commented on doc/moderation.rst
> +  provide help, but indimidated by a compiler codebase and uncertain how to even
```suggestion
  provide help, but is intimidated by the compiler codebase and uncertain how to even
```

2021-12-27 20:33 UTC, haxscramper commented
Also moved `contributing.rst` to `.github/contributing.rst` until GitHub can work with `doc/contributin.rst`

2021-12-27 20:46 UTC, alaviss commented
> Also moved `contributing.rst` to `.github/contributing.rst` until GitHub can work with `doc/contributin.rst`

This part should be done separately.

And wouldn't this make the contributing guide gone from the built website?

2021-12-27 20:48 UTC, haxscramper commented
> And wouldn't this make the contributing guide gone from the built website?

No, I moved add added `.. include`

2021-12-27 20:49 UTC, haxscramper commented
> This part should be done separately.

done

2021-12-27 22:30 UTC, saem requested changes
For the commit message, I think the formatting got messed up -- github "helping".

```
doc: 'PRs are welcome' reply recommendations

Elaborate on alternatives to 'PRs are welcome' style replies so we invite contribution. This
avoids it from being dismissive. Update itself explains the rest.
```

I'm good to merge after that.

2021-12-28 06:48 UTC, haxscramper commented
bors r+

2021-12-28 07:15 UTC, merged