Removed Unused PrintRopeCacheStats
nim-works/nimskull pull request #195
Opened 2022-01-22 20:43 UTC by canelhasmateus

## Summary
* what changed and how?

Removed  PrintRopeCacheStats

* why are we changing it?

PrintRopeCacheStats as declared as a const false. Only had one usage, acting as a guardian to a when block that references undeclared variables.

Last Modified 9 years ago, setting to true crashes the compiler.

## Details
* info that couldn't fit into the summary
* relevant details; tricky parts
* anything else

Fixes full_issue_url

---

## Notes for Reviewers
* leave additional context for reviewers
* maybe specific requests or areas of focus

<!--
Pull Request(PR) Help

Before Merge Ensure:
* title reads like a short changelog line entry
* code includes tests and is documented
* leave the source better than before, but split out big reformats

See contributor (guide)[https://nim-works.github.io/nimskull/contributing.html]
for details, especially if you're new to this project.

Tips that make PRs easier:
* for big/impactful changes, start with chat/discussions to refine ideas
* refine the pull request message over time; don't have to nail it in one go
* handle the single commit message requirement at the end of review

2022-01-22 23:57 UTC, saem commented
Hi @canelhasmateus -- thanks for the PR (sorry about the template 😞)

Quick thing for the commit message, could you format it according to the contribution guidelines, [direct link to relevant section](https://nim-works.github.io/nimskull/contributing.html#pr-and-commit-message-guidelines-commit-message-guidelines). Relevant bit being first line is 50 chars or less, and body is 72 chars or less per line.

----
Aside, sorry you're running into the first use of the PR template. 😬 Bors will shove that into the merge PR, it's probably easy enough to fix up the commit message first, then copy that into the PR body -- mind the line/thematic break for CI.

Obviously the text of the PR template isn't clear enough, anything that might help you arrive at the above conclusions yourself? I need some of your feedback with it to help fix. Thanks.

2022-01-23 00:10 UTC, canelhasmateus commented
Changes done. Is this enough?
Which conclusions are you referring to?
The commit message character limits are clear ( although i'm not aware of the reason )
If you're referring to the clearing up of the pr body, I believe a Initial header alluding to these point would be enough. Something along the lines

" 
Please don't fill below, just use it as a template or guideline to write your pr request. 
Our CI includes the PR body in the merge, so keep only what you'd like to read in a commit message.



"

( The spacing is intentional, as to have only the header message in the first rendered text box )

2022-01-23 01:33 UTC, saem commented on compiler/front/main.nim
> -  when PrintRopeCacheStats:
I did a quick search and it seems there are some global variables left around `gCacheTries` for one.

2022-01-23 01:34 UTC, saem requested changes
Found some more dead code.

Might be possible to get the stats working again if it's a matter of the global not being initialized.

What's the trace?

2022-01-23 01:34 UTC, saem commented
Thanks for the template review!

2022-01-23 01:45 UTC, canelhasmateus commented
Adding a import utils/rope fixes the problem.

trace below ( but its just standard 'not declared' shenanigans. )
Will change the pr accordingly.

2022-01-23 02:01 UTC, saem approved these changes
bors r+

2022-01-23 02:04 UTC, saem commented
bors cancel

2022-01-23 02:52 UTC, saem requested changes

2022-01-23 02:52 UTC, saem commented on compiler/front/main.nim
> +    import utils/ropes
```suggestion
  import utils/ropes
```
fixing the indentation, this should be compiler code base standardizes on two space indent.

2022-01-23 04:13 UTC, saem approved these changes

2022-01-23 04:13 UTC, saem commented
bors r+

2022-01-23 04:52 UTC, merged