Fixed generic distinct conversion proc calls
nim-works/nimskull pull request #3
Opened 2021-10-24 22:50 UTC by beef331

2021-10-24 23:17 UTC, saem requested changes

2021-10-24 23:17 UTC, saem commented on compiler/jsgen.nim
> +proc genSymAddr(p: PProc, n: PNode, typ: PType, r: var TCompRes) =
Can haz doc comments for the uninitiated?

2021-10-24 23:17 UTC, saem commented on compiler/jsgen.nim
> +      # make addr() a no-op:
It's that because they're already refs in JS land?

2021-10-24 23:17 UTC, saem commented on compiler/jsgen.nim
> +    case n[0].kind
Why do we look at the first child?

2021-10-24 23:17 UTC, saem commented on compiler/types.nim
> +      a = a.skipTypes({tyDistinct, tyGenericInst})
Skip types is much better!

Just wondering if we're missing any others? 🤔

2021-10-24 23:17 UTC, saem commented on tests/converter/texplicit_conversion.nim
> +block: # Test for nkconv
A few words describing what the spec should be/is would help teach people the spec and/or build it out as we go in an incremental fashion.

2021-10-24 23:17 UTC, saem commented on tests/distinct/tdistinct.nim
> +block: #17322
I'd prefer we keep nim issue references only for deep dive, but being in information into nimskull.

2021-10-24 23:49 UTC, beef331 commented on compiler/types.nim
> +      a = a.skipTypes({tyDistinct, tyGenericInst})
Added a `skipDistincts` to make it easier to handle all cases when wanting to skip distincts, still need to replace any uses of skipTypes with it.

2021-10-25 00:01 UTC, saem approved these changes

2021-10-25 00:01 UTC, merged