doc: add documentation describing CI internals
nim-works/nimskull pull request #394
Opened 2022-08-03 21:09 UTC by alaviss

## Summary

This PR adds internal documentation for the CI system. This should enable contributors to have an easier time contributing to the CI system as well as troubleshooting problems arise from its usage.

2022-08-04 08:26 UTC, saem reviewed
Overall, really good.

Added some comments here and there.

2022-08-04 08:26 UTC, saem commented on doc/ci.rst
> +There are several reasons for why this happens:
```suggestion
This is a build reproducibility test failure, comparing a builds from a git clone vs source archive -- yes, these can differ. See more on reproducible builds here (insert link).

There are several reasons for why this happens:
```

It's a bit over explaining but reproducible builds tests aren't a common thing and people might need a "slow down, here is what it means", before trying to fix it.

Not a hard suggestion, I'm just recommending it.

2022-08-04 08:26 UTC, saem commented on doc/ci.rst
> +* A cosmic ray hit the CI test system and make it generate slightly different
```suggestion
* A cosmic ray hit the CI test system and made it generate a slightly different
```

2022-08-04 08:26 UTC, saem commented on doc/ci.rst
> +To get more details on the error, open the failing workflow run and go to
```suggestion
To get more details about the error, open the failing workflow run and go to
```

2022-08-04 08:26 UTC, saem commented on doc/ci.rst
> +"differences between binary from source archive and git". This contains HTML
```suggestion
"differences between binary from source archive and git". This contains an HTML
```

2022-08-04 08:26 UTC, saem commented on doc/ci.rst
> +PRs to be merged are tested to make sure that the compiler build remains
Ah, you covered it here, different kind of reproducibility though.

2022-08-04 08:26 UTC, saem commented on doc/ci.rst
> +* Your changes introduces undeterministic variables like the current
```suggestion
* Your changes introduces nondeterministic variables like the current
```

2022-08-04 08:26 UTC, saem commented on doc/ci.rst
> +  ordering is undeterministic and files must be ordered in memory before they
```suggestion
  ordering is nondeterministic and files must be ordered in memory before they
```

2022-08-04 08:26 UTC, saem commented on doc/ci.rst
> +The only way to get code to |NimSkull|'s development branch is via PRs, and CI
```suggestion
The only way to get code into |NimSkull|'s development branch is via PRs, and CI
```

2022-08-04 08:26 UTC, saem commented on doc/ci.rst
> +5. The "Publish" pipeline is run and deploy the rendered documentation and binaries
```suggestion
5. The "Publish" pipeline deploys the rendered documentation and binaries
```

2022-08-04 08:26 UTC, saem commented on doc/ci.rst
> +With this lifecycle, CI make a few assumptions on the code state:
```suggestion
This lifecycle has a number of useful properties which we use in our approach to CI as follows:
```

2022-08-04 08:26 UTC, saem commented on doc/ci.rst
> +This section provides an in-depth view on the design of each pipeline and the
```suggestion
This section describes the design of each pipeline and the
```

2022-08-04 08:26 UTC, saem commented on doc/ci.rst
> +* Verify that the compiler, tooling and standard library test suite passes
```suggestion
* Verify that the compiler, tools, and standard library test suites pass
```

2022-08-04 08:26 UTC, saem commented on doc/ci.rst
> +* Verify that a source archive could be built.
```suggestion
* Verify that a source archive was built.
```

2022-08-04 08:26 UTC, saem commented on doc/ci.rst
> +  * Whether building the compiler and tools from the source archive works.
```suggestion
  * Compiler and tools built from the source archive work.
```

2022-08-04 08:26 UTC, saem commented on doc/ci.rst
> +  * Whether the result of building from the source archive is identical to
```suggestion
  * Building from source archive is identical to
```

2022-08-04 08:26 UTC, saem commented on doc/ci.rst
> +    building from the git clone.
```suggestion
    building from a git clone.
```

2022-08-04 08:26 UTC, saem commented on doc/ci.rst
> +* Render HTML documentation for uploading to Github Pages.
```suggestion
* Render HTML documentation for upload to Github Pages.
```

2022-08-04 08:26 UTC, saem commented on doc/ci.rst
> +To support that, this pipeline exports the build result as Github Artifacts,
```suggestion
To support publishing, this pipeline exports the build result as Github Artifacts,
```

2022-08-04 08:26 UTC, saem commented on doc/ci.rst
> +and these are the artifacts meant for consumption by other pipelines:
```suggestion
which are used by other pipelines, these artifacts are:
```

2022-08-04 08:26 UTC, saem commented on doc/ci.rst
> +* "release manifest tool": This artifact contains a built copy of
```suggestion
* "release manifest tool": contains a built copy of
```

2022-08-04 08:26 UTC, saem commented on doc/ci.rst
> +* "release binaries": Binaries built via ``koch unixrelease`` and their JSON
```suggestion
* "release binaries": built via ``koch unixrelease`` and their JSON
```

2022-08-04 08:26 UTC, saem commented on doc/ci.rst
> +* "source archive": The source archive generated from the git clone.
```suggestion
* "source archive": generated from the git clone.
```

2022-08-04 08:26 UTC, saem commented on doc/ci.rst
> +In order to maximize throughput, steps are splitted into multiple dependent
```suggestion
In order to maximize throughput, steps are split into multiple dependent
```

2022-08-04 08:26 UTC, saem commented on doc/ci.rst
> +* Unrelated steps to be executed in parallel on multiple VMs.
```suggestion
* Unrelated steps can be executed in parallel on multiple VMs.
```

2022-08-04 08:26 UTC, saem commented on doc/ci.rst
> +  respectively. These actions allow a job to upload its workspace, that is, all
```suggestion
  respectively. These actions allow a job to upload its workspace, all
```

2022-08-04 08:26 UTC, saem commented on doc/ci.rst
> +  so that they can be run independently.
```suggestion
  so they run independently.
```

2022-08-04 08:26 UTC, saem commented on doc/ci.rst
> +* "binaries from source archive": This contains binaries built from the source
```suggestion
* "binaries from source archive": Contains binaries built from the source
```

2022-08-04 08:26 UTC, saem commented on doc/ci.rst
> +* ``pre_run`` outputs: The ``pre_run`` job provides a lot of data that dictates
```suggestion
* ``pre_run`` outputs: The ``pre_run`` job provides data that dictates
```

2022-08-04 08:26 UTC, saem commented on doc/ci.rst
> +information on the testing criterias.
```suggestion
information on the testing criteria.
```

2022-08-04 08:26 UTC, saem commented on doc/ci.rst
> +This pipeline is used to publish build results from prior run of the "Build and
```suggestion
Publishes build results from the prior run of the "Build and
```

2022-08-04 08:26 UTC, saem commented on doc/ci.rst
> +put into the way it's action.
```suggestion
put into any changes to it.
```

2022-08-04 08:26 UTC, saem commented on doc/ci.rst
> +Only one instance of this pipeline might be run at any given time, due to its
This should be combined with the above as I believe this is the key thing to be careful about

2022-08-04 08:26 UTC, saem commented on doc/ci.rst
> +  interested in things like test suite runs rather than whether a source archive
Simmering more to the affect of

```suggestion
  If the tests don't pass reproducibility is a moot point
```

2022-08-04 08:26 UTC, saem commented on doc/ci.rst
> +  pinned OS. This avoid breakage due to random differences in software version.
```suggestion
  OS. This avoid breakage due to random differences in software version.
```

2022-08-04 08:26 UTC, saem commented on doc/ci.rst
> +* Prefer using a version tag if possible. This makes sure that errorneous updates
```suggestion
* Prefer using a version tag. This makes sure that errorneous updates
```

2022-08-04 08:26 UTC, saem commented on doc/ci.rst
> +and will convert all messages generated by the Nim compiler into annotations.
```suggestion
and will convert all messages generated by the |Nimskull| compiler into annotations.
```

2022-08-04 08:26 UTC, saem commented on doc/ci.rst
> +have rather comprehensive built-in documentation, please refer to that for
```suggestion
has rather comprehensive built-in documentation, please refer to that for
```

2022-08-04 08:26 UTC, saem commented on doc/docs.rst
> +  | The documentation describes how CI is implemented and common troubleshooting steps for failures. Recommended read if you are looking to work on the CI infrastructure.
```suggestion
  | Describes how CI is implemented and steps for troubleshooting common failures. Required reading for those looking to work on the CI infrastructure.
```

2022-08-04 09:57 UTC, haxscramper approved these changes
Aside from comments by @saem I don't see anything that should be changed - looks pretty good to me.

2022-08-04 18:14 UTC, zerbina reviewed
Also looks good to me!

I left some small adjustment suggestions.

2022-08-04 18:14 UTC, zerbina commented on doc/ci.rst
> +When tests of this category fails, the culprit usually are:
```suggestion
When tests of this category fail, the culprit usually is:
```

2022-08-04 18:14 UTC, zerbina commented on doc/ci.rst
> +to read when the differences are large. To help with this, companion HTML
```suggestion
Text diffs are generated, but there is no highlighting and they can be hard
to read when the differences are large. To help with this, companion HTML
```

2022-08-04 18:14 UTC, zerbina commented on doc/ci.rst
> +2. The PR enters the merge queue and is merged to a staging branch. Multiple
```suggestion
2. The PR enters the merge queue and is merged to a ``staging`` branch. Multiple
```

2022-08-04 18:14 UTC, zerbina commented on doc/ci.rst
> +   to staging head commit.
```suggestion
4. Assuming that the ``staging`` branch passes all tests, ``devel`` is
   fast-forwarded to the ``staging`` head commit.
```

2022-08-04 18:14 UTC, zerbina commented on doc/ci.rst
> +  ``staging`` will become new ``devel``:
```suggestion
  ``staging`` will become the new ``devel``:
```

2022-08-04 18:14 UTC, zerbina commented on doc/ci.rst
> +  * This allows us to run crucial evaluations task on ``staging`` only, and
```suggestion
  * This allows us to run crucial evaluation tasks on ``staging`` only, and
```

2022-08-04 18:14 UTC, zerbina commented on doc/ci.rst
> +* Only "light" tests has to be run on PRs to help developers debug their code
```suggestion
* Only "light" tests have to be run on PRs to help developers debug their code
```

2022-08-04 18:14 UTC, zerbina commented on doc/ci.rst
> +of publishing its generated data. That part is handled by the "Publish"
```suggestion
of publishing it's generated data. That part is handled by the "Publish"
```

2022-08-04 18:14 UTC, zerbina commented on doc/ci.rst
> +once a PR enters staging.
```suggestion
once a PR enters ``staging``.
```

2022-08-04 21:24 UTC, alaviss commented on doc/ci.rst
> +* Verify that a source archive could be built.
Wouldn't "was built" means that it was built earlier by something else and not checking if it can be built successfully?

2022-08-06 18:57 UTC, saem requested changes
One or two minor changes, the rest are not necessary.

This is awesome. 🤩

2022-08-06 18:57 UTC, saem commented on doc/ci.rst
> +* Annotations are generated for test failures:
```suggestion
* Annotations (a GitHub feature) are generated for test failures:
```

On the phone and I can recall link syntax but worth linking to a GH help page.

2022-08-06 18:57 UTC, saem commented on doc/ci.rst
> +deterministic with regards to the environment. For more information, see
```suggestion
deterministic with regards to the environment. To learn more about why reproducible builds matter and the concepts, see
```

Something like that helps indicate that it's general knowledge and not specific to us. This is not a hard suggestion.

2022-08-06 18:57 UTC, saem commented on doc/ci.rst
> +When tests of this category fail, the culprit usually is:
```suggestion
When tests of this category fail, the culprit usually are:
```

My restructured text formating reading skills are rusty, but I believe there are two items in the list that follows.

2022-08-06 18:57 UTC, saem commented on doc/ci.rst
> +* Verify that a source archive could be built.
Yes, my reading of this doc this far gave the impression that that's what happened.

If that's not the case then I believe "can be" would be more appropriate.

2022-08-06 18:57 UTC, saem commented on doc/ci.rst
> +* Unrelated steps can be executed in parallel on multiple VMs.
```suggestion
* Unrelated steps to execute in parallel on multiple VMs.
```

2022-08-07 03:47 UTC, saem approved these changes
Bots r+

2022-08-07 04:46 UTC, alaviss commented
bors r+

2022-08-07 06:39 UTC, merged