sem: fix parsing different kinds of import statements
nim-works/nimskull pull request #757
Opened 2023-06-11 21:00 UTC by iacore

## Summary
Now the following file can be parsed correctly.
```nim
import options
import os, options
from os import joinPath, `/`
import os except joinPath, `/`
```

## Notes for Reviewers
- no test added yet

2023-06-12 02:15 UTC, saem requested changes
This is a nice fix. I left some recommendations for the test.

Please update the PR description and I can merge it.

2023-06-12 02:15 UTC, saem commented on tests/lang_callable/macros/tnimskull757.nim
> +discard """
I'd rename this file `ttyped_importstmts_nimskull757.nim`

This would setup a nice convention `ttyped_<nodekind>...`, pretty sure there is a better home to suss out for these tests in the future.

2023-06-12 02:15 UTC, saem commented on tests/lang_callable/macros/tnimskull757.nim
> +  output: '''
```suggestion
  description: "Test import statements are properly analysed"
  output: '''
```

My description itself isn't the best, here is a recent example of a good one liner from Zerbina's PR: https://github.com/nim-works/nimskull/pull/756/files#diff-e37ff9cec4f49c315bfae4bcdc98161e8ba8f4db3b04346b2c51ae7c38ea7bbbR4

2023-06-12 12:07 UTC, iacore commented on tests/lang_callable/macros/tnimskull757.nim
> +discard """
I've moved it to a better place

2023-06-12 15:00 UTC, zerbina commented
Regarding the PR description, for PRs that fix something, I think that the description should answer the following questions:
- what didn't work? what failed? what was wrong?
- (depending on the problem) why didn't it work?
- what is changed to make it work?

---

When writing the description, it can help to ask oneself the above question (and follow up questions) and then try to answer them, like so (using this PR as an example):

*Question:* what was wrong?
*Answer:* `from x` and `import x except y` were always represented as `nkImportStmt` in typed

*Question:* what were the consequences?
*Answer:* there was an irreversible loss of information and the produced typed AST was semantically wrong. The problematic AST was not able to roundtrip through semantic analysis, and other consumers (such as passes, macros, or external tools) were not able to properly inspect import statement

*Question:* what is changed?
*Answer:* the producers of the relevant typed AST (`evalFrom` and `evalImportExcept`) are changed to use the same node kind as that of the input. Since these node kinds previously did not reach `mirgen` (but now they do), `mirgen` now needs to handle (i.e., discard) them 

The answers can then be used as the basis for writing the description.

2023-06-12 16:18 UTC, iacore commented
Is the typed AST not used for codegen? I'm confused why the compiler works with this bug.

Also, I don't know *that* much about nimskull

2023-06-12 17:17 UTC, saem commented
> Is the typed AST not used for codegen? I'm confused why the compiler works with this bug.

It is used for codegen, but it's not the only input. The compiler pass system has two key data structures built up and available for codegen, besides the AST. They are `modulegraphs.ModuleGraph` and `options.ConfigRef`. In particular the former collects a lot of information about modules, symbol tables, etc that can be used in lieu of information less conveniently encoded within the AST itself. In this case the imports a particular module requires. That's why codegen was able to proceed and the bug was never discovered.

With your fix, we could build upon it (separate PR) that at the very least cross references imports in the AST vs those derived from other sources.

> Also, I don't know _that_ much about nimskull

Not a problem, can help answer questions and lend a hand. This also helps highlight things I, or others, take for granted and could be improved over time.

2023-06-12 19:11 UTC, iacore commented
@saem can this be merged?

2023-06-12 20:18 UTC, saem commented
@iacore I've updated the PR title/description, please take a look at the content and format.

The title is 50 chars, describing the change. The content contains the `summary` and `details` headings, the former describes the net result today, and the latter describes what changed and how in more detail. The body is formatted to 72 chars lines. The formatting will ensure a legible commit message.

Once you've had a chance to read the updated PR, ping me here or in chat and I can trigger the merge.

2023-06-12 22:50 UTC, saem commented
/merge

2023-06-12 22:50 UTC, saem approved these changes

2023-06-12 22:51 UTC, saem commented
Just want to do one more quick thing before merge.

2023-06-12 23:04 UTC, saem commented
/merge

2023-06-12 23:25 UTC, saem commented
/merge

2023-06-13 01:55 UTC, saem commented
/merge

2023-06-13 02:28 UTC, merged