memalloc: remove compile time sizeof check
nim-works/nimskull pull request #766
Opened 2023-06-17 05:35 UTC by mrgaturus

## Summary
* what changed and how?
Removed compile time sizeof check from `create` and `createU` procs
* why are we changing it?
unsafe raw allocations may be used for better FFI on C libraries, however some types can be imported from C and have sizes/align which might differ from nim type semantics, then those types can be imported as opaque with help of `{.importc, header.}` but those are not `{.completeStruct.}` and cannot be used with compile time sizeof.

## Details
* info that couldn't fit into the summary
\- `createShared`, `createSharedU`, `resize`, `resizeShared` don't have the sizeof check and do the same thing of those two procs
\- `new` proc for alloc ref types doesn't use a sizeof check, so what is the point of using a sizeof check on unsafe raw allocations?
* relevant details; tricky parts
the [C standard](https://pubs.opengroup.org/onlinepubs/007904975/functions/malloc.html) said something about `free(malloc(0))`:

> malloc() shall return a pointer to the allocated space. If size is 0, either a null pointer or a unique pointer that can be successfully passed to [free()](https://pubs.opengroup.org/onlinepubs/007904975/functions/free.html) shall be returned.

---

## Notes for Reviewers
* leave additional context for reviewers
all usable procs of memalloc are very unsafe because all implications of using raw pointers such memory leaks or use-after-free if there is an unbalanced usage of allocation and deallocation
* maybe specific requests or areas of focus
we need to see how to deal with those foreign types at compile time, probably a way that can show us if a type has foreign stuff would be a good idea
<!--
Pull Request(PR) Help

Before Merge Ensure:
* title reads like a short changelog line entry
* code includes tests and is documented
* leave the source better than before, but split out big reformats

See contributor (guide)[https://nim-works.github.io/nimskull/contributing.html]
for details, especially if you're new to this project.

Tips that make PRs easier:
* for big/impactful changes, start with chat/discussions to refine ideas
* refine the pull request message over time; don't have to nail it in one go
* handle the single commit message requirement at the end of review

2023-06-17 17:15 UTC, zerbina requested changes
Thank you for contributing!

The checks were introduced by https://github.com/nim-lang/nim/pull/19032, which was implemented as a response to [this](https://github.com/nim-lang/nim/issue/19000) issue (`create(UncheckedArray)` having surprising behaviour). Eventually, Nim faced the same problem as you are doing now (using `create` with a type that has a non-compile-time known size leads to a compilation error) and the checks were thus removed again (https://github.com/nim-lang/Nim/pull/20518).

Disallowing the use of `create` with `UncheckedArray` (or dynamically sized objects in general) does make sense, and I think the `sizeof` checks should be replaced with `T is UncheckedArray`. That won't prevent the problematic use of dynamically sized objects like:
```nim
type Obj = object
  i: int
  data: UncheckedArray[int]
```
with `create`, but it will at least detect and disallow direct usage with `UncheckedArray`.

In addition, please add a test for `create` and `createU` with an imported type, so that it is ensured that the change works as expected.

2023-06-18 05:36 UTC, mrgaturus commented
forbid UncheckedArray without ptr and ref makes sense because manipulating raw allocs with UncheckedArray is a common pattern, it think a proc called `toUncheckedArray` would make some elegance:
```nim
let a = create(cint, 2000).toUncheckedArray
# let a  = cast[ptr UncheckedArray[cint]](create(cint, 2000))
a[10] = 1234
a.dealloc()
```

2023-06-18 16:34 UTC, zerbina reviewed
Thanks. I left some small requests regarding the code and tests.

When you're ready, please also update the PR message to reflect what is changed, as it is the message that will be used for the commit merged into the `devel` branch.

For the PR message, I think it makes sense to include a small mention of the reason behind the now removed `sizeof` check.

2023-06-18 16:34 UTC, zerbina commented on lib/system/memalloc.nim
> +        {.error: "UncheckedArray[T] does not have size, use T instead".}
Could you remove the redundant wrapping in a `static` block (here and in the other places)?

2023-06-18 16:34 UTC, zerbina commented on lib/system/memalloc.nim
> +        {.error: "UncheckedArray[T] does not have size, use T instead".}
```suggestion
        {.error: "UncheckedArray[T] has no size. Use T instead".}
```
(also applies to the other three places)

2023-06-18 16:34 UTC, zerbina commented on tests/system/talloc3.nim
> +"""
```suggestion
  description: '''
    Using the higher-level allocation procedures with types that have a size not
    known at the NimSkull side must work
  '''
"""
```
In addition, please rename the test to something more descriptive (maybe `talloc_with_unknown_size.nim`).

2023-06-18 16:34 UTC, zerbina commented on tests/system/talloc3.nim
> +  M128d* {.importc: "__m128d", header: "emmintrin.h".} = object
```suggestion
type
  Obj {.exportc.} = object

# make sure the type is really exported:
var use: Obj

type
  Imported {.importc: "Obj", nodecl.} = object
    # opaque type
```
This makes the test less dependent on C implementation details.

2023-06-18 16:34 UTC, zerbina commented on tests/system/talloc3.nim
> +  MapMixed = UncheckedArray[MixedPixel]
```suggestion
  Native = object
    field: int
  WithImported = object
    field: Imported
  WithBitField = object
    field {.bitsize: 4.}: cint
  Mixed = object
    r {.bitsize: 4.}: cint
    g: int
    b: Imported
  ArrayNative       = UncheckedArray[Native]
  ArrayWithImported = UncheckedArray[WithImported]
  ArrayWithBitField = UncheckedArray[WithBitField]
  ArrayMixed        = UncheckedArray[Mixed]
```
I think that this makes the test slightly easier to read and comprehend.

2023-06-19 13:20 UTC, zerbina approved these changes
@mrgaturus Nice work. I have reworded the PR message to be a bit shorter, fit in with the general commit message style, and to have a line length of 72.

If you're okay with the changes, please notify me here or on Matrix and I'll kick off the merge.

2023-06-19 16:57 UTC, mrgaturus commented
@zerbina Thank you for your feedback. That is ready for merge 🚀

2023-06-19 17:45 UTC, zerbina commented
/merge

Onto the `devel` branch it goes :D

2023-06-19 18:11 UTC, saem commented
I just got back from the gym, with merging this on my mind, pleasantly surprised to see it already on the way. :D

Thanks for seeing this through, @mrgaturus and @zerbina.

2023-06-19 19:40 UTC, zerbina commented
/merge

2023-06-19 20:24 UTC, merged