Fix: typo in type names
nim-works/nimskull pull request #844
Opened 2023-08-17 16:51 UTC by iacore

some type names are not uppercased

2023-08-17 20:30 UTC, zerbina requested changes
Thank you for the PR. I've updated the title to better reflect what is changed.

Please also update the PR message regarding what works now (the `marshal` module could already be compiled previously, it only failed when `--styleCheck:error` is enabled) and ensure that it adheres to the rules mentioned in the template.

For making sure that it really does work now, please also change `tests/stylecheck/tstyle_imports.nim` such that it imports the `marshal` module -- you only need to uncomment line 56.

2023-08-19 13:22 UTC, zerbina commented
> @zerbina says that `std/marshal` module could already be compiled previously, it only failed when `--styleCheck:error` is enabled. I think this is the default behavior now, since it doesn't compile by default.

`--styleCheck:error` is not the default. See, for example, the `stdlib/formats/tmarshal.nim` test, which imports the `marshal` module without configuring style checks.

The reason importing the module caused problems for you is that you tried to import the module in the compiler, where standard style *is* enforced (see `compiler/nim.cfg`).

2023-08-19 13:32 UTC, zerbina commented
Apart from the PR message structure and formatting, this is good to go.

2023-08-20 13:38 UTC, iacore commented
> Apart from the PR message structure, content, and formatting, this is good to go.

Can you fix the PR message for me? I don't know what it is supposed to look like.

2023-08-20 20:40 UTC, zerbina commented
Okay, I will do so tomorrow.

2023-08-21 15:45 UTC, zerbina commented
I've updated the message. The problems with the previous one were that:
- the lines had more than 72 characters
- the description implied that `std/marshal` couldn't be compiled previously, which is incorrect

@iacore If you're okay with the changes, please ping me, and I'll start the merge.

2023-08-21 16:14 UTC, iacore commented
@zerbina this is fine.

2023-08-21 17:32 UTC, zerbina approved these changes

2023-08-21 17:33 UTC, zerbina commented
/merge

2023-08-21 18:18 UTC, merged