[WIP] Make Arc decrefs and increfs atomic
nim-works/nimskull pull request #88
Opened 2021-12-01 16:17 UTC by shayanhabibi

As per the discussion on shared refs and arc, this fix will prevent any undefined behavior occuring.

The idea is to:

- [ ] Have all atomic operations on ref count changes when threads:on

- [ ] Make atomic operations opt-out using a Owned[T] type

- [ ] Include a one file test that demonstrates the behavior before/after

2021-12-02 01:56 UTC, alaviss reviewed
I think we should not go with relaxed atomics until we can verify that everything works as expected.

2021-12-02 23:31 UTC, shayanhabibi commented
The dec and incs must be ordered correctly; the load can be relaxed as it will not be able to pass any dec/incs due to their stricter ordering. The subsequent atomicdec being ordered prevents the load moving forward. Since the load is used as the condition for entering the block, should be aiight. Else I'll change it to acqrel

2021-12-03 00:31 UTC, alaviss commented
> The subsequent atomicdec being ordered prevents the load moving forward.

I guess you haven't noticed this:

https://github.com/nim-works/nimskull/blob/989adc65731d01b29ec34520d17ffaa233e907f0/lib/system/atomics.nim#L228-L233

2021-12-03 01:07 UTC, shayanhabibi commented
F*** 🤣 I assumed seqcst is the default!

Hahaha I made an ass out of myself. Thank you bb ❤️ I'll fix it up

2021-12-07 15:23 UTC, disruptek requested changes
If you're going to touch every line in `atomics` why not improve it -- do we need to be exporting a distinct cint for AtomMemModel or can we make the API idiomatic, with an enum?  These variables and constants are code smell; you can hide them in here with a converter if you're lazy.  Also not a fan of the `barrier` template.  Yikes.

2021-12-07 15:23 UTC, disruptek commented on lib/system.nim
> +  #   ## Atomic decrement of `memLoc`. Returns the value after the operation.
Prefer `when false:` and document why these are removed.

2021-12-07 15:23 UTC, disruptek commented on lib/system/arc.nim
> +  # We want to use atomic operations when threading is on
Add a period.

2021-12-07 15:23 UTC, disruptek commented on lib/system/arc.nim
> +      dec(x, y)
Move it out and reuse it below.  Add a comment or more descriptive name.  Why not use `typed`?

2021-12-07 15:23 UTC, disruptek commented on lib/system/arc.nim
> +
Comment or rename to be more descriptive.

2021-12-07 15:27 UTC, disruptek commented
Also, I would favor a single `when hasThreadSupport:` where you define two sets of templates; you can document the differences there and explain why they exist instead of scattering the conditionals in templates throughout the code.

2021-12-08 01:22 UTC, shayanhabibi commented
> If you're going to touch every line in `atomics` why not improve it -- do we need to be exporting a distinct cint for AtomMemModel or can we make the API idiomatic, with an enum? These variables and constants are code smell; you can hide them in here with a converter if you're lazy. Also not a fan of the `barrier` template. Yikes.

Bloody CLRF.

2022-07-20 14:35 UTC, closed without merging