proc `==` TlineInfo exact match
nim-works/nimskull pull request #880
Opened 2023-09-08 07:15 UTC by bung87

## Summary
* what changed and how?
* why are we changing it?

## Details
* info that couldn't fit into the summary
* relevant details; tricky parts
* anything else

Fixes full_issue_url

---

## Notes for Reviewers
* leave additional context for reviewers
* maybe specific requests or areas of focus

<!--
Pull Request(PR) Help

Before Merge Ensure:
* title reads like a short changelog line entry
* code includes tests and is documented
* leave the source better than before, but split out big reformats

See contributor (guide)[https://nim-works.github.io/nimskull/contributing.html]
for details, especially if you're new to this project.

Tips that make PRs easier:
* for big/impactful changes, start with chat/discussions to refine ideas
* refine the pull request message over time; don't have to nail it in one go

2023-09-08 15:36 UTC, zerbina requested changes
Since it's the same as the lifted, you can remove the manual `==` implementation as a whole.

Also, could you elaborate on what you mean by "stop historical un-aware problem"? Apart from the simplification, which makes sense, what is the reason for this change?

2023-09-08 15:42 UTC, bung87 commented
> Since it's the same as the lifted, you can remove the manual `==` implementation as a whole.
> 
> Also, could you elaborate on what you mean by "stop historical un-aware problem"? Apart from the simplification, which makes sense, what is the reason for this change?
 `==` compare to line is anti-intuition

2023-09-08 16:19 UTC, zerbina commented
> `==` compare to line is anti-intuition

While I think the change is good, I don't think that the previous `==` behaviour is un-intuitive. The type is named `TLineInfo`, so the comparison returning true for two instances that point to the same line makes sense.

2023-09-08 16:32 UTC, bung87 commented
> > `==` compare to line is anti-intuition
> 
> While I think the change is good, I don't think that the previous `==` behaviour is un-intuitive. The type is named `TLineInfo`, so the comparison returning true for two instances that point to the same line makes sense.

while if user hover the `==` they can have a look to its definition, however if the expression use `!=` it just show system template.

2023-09-08 16:53 UTC, zerbina commented
> while if user hover the `==` they can have a look to its definition, however if the expression use `!=` it just show system template.

Hm, I'm not sure I understand the relation this has to the equality operation only considering the line number. Could you elaborate?

2023-09-08 17:06 UTC, bung87 commented
it's not a short path to track, how the user know the type have custom `==`
```nim
template `!=`*(x, y: untyped): untyped =
  ## Unequals operator. This is a shorthand for `not (x == y)`.
  not (x == y)
```

2023-09-08 17:50 UTC, zerbina commented
Are you saying that `==` for `TLineInfo` not considering the column information is un-intuitive because the `!=` operator, as a consequeunce, is also not considering it?

To be clear, I'm only trying to understand your reasoning behind this change.

2023-09-08 17:55 UTC, bung87 commented
yes, without editor support I didn't aware there's custom `==` proc

2023-09-08 18:17 UTC, zerbina commented
Hm, okay. In my opinion, that could have also been mitigated via a less impactful change (e.g., by moving the equality operator and `exactEquals` into `lineinfos` and then documenting the quirk on `TLineInfo`).

In any way, have you verified that there are no usage sites left where the old equality behaviour is relied on?

2023-09-08 18:25 UTC, bung87 commented
I've find reference on `==` like 5 results, `msgs.getContext` maybe the only place need old behavior for a little bit better performance

2023-09-08 18:37 UTC, zerbina commented
For finding all usages or possible usage, you can annotate the old `==` procedure with `.deprecated`, which will show warnings at each usage site.

I've found two places where the changed `==` procedure causes a change in behaviour:
1. in `vmprofiler.leaveImpl` (the `li notin data` query)
2. in `nilcheck.derefWarning` (the `n.info in ctx.warningLocations` query)

The second one is maybe minor (only increasing the amount of warnings produced), but the first one is not, as the profiler wants to associate the time-taken with a line, and not a precise line + column.

2023-09-08 19:02 UTC, bung87 commented
nice! so if this going forward, only need fix `vmprofiler.leaveImpl` by using custom type without col  I guess?

2023-09-08 22:13 UTC, zerbina commented on compiler/ast/lineinfos.nim
> +  FileLinePar* = tuple
```suggestion
  SourceLinePosition* = tuple
    ## Identifies a line in a source file. Only intended for use by
    ## the profiler.
```
In general, please make sure to document new types and procedures.

2023-09-08 22:13 UTC, zerbina commented on compiler/front/options.nim
> +    data*: TableRef[FileLinePar, ProfileInfo]
```suggestion
    data*: TableRef[SourceLinePosition, ProfileInfo]
```

2023-09-08 22:13 UTC, zerbina commented on compiler/front/options.nim
> +  ProfileData(data: newTable[FileLinePar, ProfileInfo]())
```suggestion
  ProfileData(data: newTable[SourceLinePosition, ProfileInfo]())
```

2023-09-08 22:13 UTC, zerbina commented on compiler/vm/vmprofiler.nim
> +    var flMax: FileLinePar
```suggestion
    var flMax: SourceLinePosition
```

2023-09-08 22:13 UTC, zerbina commented on compiler/vm/vmprofiler.nim
> +                       toMsgFilename(conf, flMax.fileIndex) & "(" & $flMax.line & ")" & "\n"
```suggestion
    result.toLocation(toMsgFilename(conf, flMax.fileIndex), flMax.line, 0)
    result.add "\n"
```
This ensures rendering of line information is implemented uniformly (through `toLocation`). For the procedure to be available, you need to import the `std/private/miscdollars` module.

2023-09-08 22:29 UTC, zerbina commented
Apart from renaming `FileLinePar` (my suggestions above), please also update the PR message. A detailed description on how a PR message should look like can be found in the contribution guidelines.

For this PR, please make sure:
- that the message and title reflect that that the PR effectively changes what a `TLineInfo` represents
- to detail the full impact (e.g., how the profiler output is different)
- that the motivation behind the change is clear and, ideally, why this way is preferred over a less impactful one

2023-09-09 01:48 UTC, bung87 commented
this doesn't change `TLineInfo` represents and  profiler output

2023-09-09 17:31 UTC, zerbina commented on compiler/vm/vmprofiler.nim
> +                       toMsgFilename(conf, newLineInfo(flMax.fileIndex, flMax.line.int, 0)) & "\n"
```suggestion
                       toMsgFilename(conf, newLineInfo(flMax.fileIndex,
                                                       flMax.line.int,
                                                       -1)) &
                       "\n"
```
Using `-1` as the column prevents the column from being rendered.

2023-09-09 17:54 UTC, zerbina commented
The new PR message is much better than the previous one. However, there are still some things that I think need adjustments:
- as I mentioned, the removal of the two procedures is a *detail* -- it doesn't summarize the impact and thus neither belongs in the title nor summary. For example, to someone not familiar with what the `==` implementation did, the removal itself is meaningless 
- it's not clear what "historical unawareness problems" means
- don't dismiss the impact of changes ("it can be ignored"), describe *why* it can be ignored

The title and summary should provide a broad overview of the impact and reasoning to both reviewers and future contributors. Language-level changes or changes to the user interface also usually go in this section.

The details section is for going into detail on the impact, what exactly changed, why it changed, what alternatives were considered (if any), etc.

2023-09-09 18:22 UTC, bung87 commented
updated, sorry for my pool English

2023-09-10 15:08 UTC, zerbina commented
> updated, sorry for my pool English

No worries, I and others can help you with writing commit messages.

I've updated the title and body according to my previous comments. In addition, the change doesn't only affect the performance of `getContext`, it also changes its behaviour. Please make sure to mention these things.

2023-09-10 15:09 UTC, zerbina approved these changes

2023-09-10 15:51 UTC, zerbina commented
/merge

2023-09-10 16:25 UTC, merged