fix `semIf` not flaged as `hasError` when get ill formed ast
nim-works/nimskull pull request #933
Opened 2023-09-30 10:41 UTC by bung87

## Summary
* fix `semIf` not flaged as `hasError` when get ill formed ast.
* without flaged as `hasError` when get ill formed ast, backward in `it[^1]`
  will cause `IndexDefect`.

## Details
* at first iteration child of node, when `semReportIllformedAst` also asign `hasError` to `true`

---

## Notes for Reviewers

<!--
Pull Request(PR) Help

Before Merge Ensure:
* title reads like a short changelog line entry
* code includes tests and is documented
* leave the source better than before, but split out big reformats

See contributor (guide)[https://nim-works.github.io/nimskull/contributing.html]
for details, especially if you're new to this project.

Tips that make PRs easier:
* for big/impactful changes, start with chat/discussions to refine ideas
* refine the pull request message over time; don't have to nail it in one go

2023-09-30 15:08 UTC, zerbina requested changes
Thank you for fixing/improving the `nkError` propagation. Is this specific problem one that you noticed as part of the LSP-related work?  

---

As is, the change is not correct. A node must only be wrapped in a wrapper `nkError` if there's an `nkError` within, but this is not necessarily the case when `semReportIllformedAst` is called here.

To fix issue properly, you need to replace the `semReportIllformedAst` call with inserting an `nkError`, like so:

```nim
hasError = true
result[i] = c.config.newError(it, PAstDiag(kind: adSemIllformedAst))
```

In addition, could you add a test?

2023-09-30 16:33 UTC, bung87 commented
yeah, recent bug fix all found during developing LSP, the server crash when outline compiler code.

2023-09-30 19:44 UTC, zerbina commented on tests/lang_callable/macros/tif_ill_formed.nim
> +  )
```suggestion
  result =
    nnkIfStmt.newTree(
      newNimNode(nnkElseExpr))
```
A minor stylistic suggestion.

2023-09-30 19:44 UTC, zerbina commented on tests/lang_callable/macros/tif_ill_formed.nim
> +  cmd: "nim check $options $file"
```suggestion
  description: '''
    Ensure that ill-formed if-statement AST created by macros is detected
  '''
  cmd: "nim check $options $file"
```
This makes it a bit clearer that other `if` AST tests should also go here.

2023-09-30 19:44 UTC, zerbina commented on tests/lang_callable/macros/tif_ill_formed.nim
> +'''
Could you use inline annotations (`#[tt.Error`) instead? They make it easier to extend this test in the future, as one doesn't have to update all line numbers.

2023-09-30 20:41 UTC, zerbina commented on tests/lang_callable/macros/tif_ill_formed.nim
> +  nimoutformat: sexp
```suggestion
  cmd: "nim check --hints:off $options $file"
  nimoutfull: "true"
```
The `sexp` mode and related testament support is a bit shaky at the moment, the general direction is to not use it for now.

2023-09-30 20:41 UTC, zerbina commented on tests/lang_callable/macros/tif_ill_formed.nim
> +               ^ (SemIllformedAst)]#
```suggestion
      newNimNode(nnkElseExpr)) #[tt.Error
               ^ illformed AST:  else: <<0th child missing for nkElseExpr >>]#
```

2023-09-30 21:42 UTC, zerbina commented on tests/lang_callable/macros/tif_ill_formed.nim
> +               ^ illformed AST:  else: <<0th child missing for nkElseExpr >>]#
```suggestion
                ^ illformed AST:  else: <<0th child missing for nkElseExpr >>]#
```
That should fix the failure.

2023-10-01 09:10 UTC, bung87 commented
well, look back into this, this is similar to https://github.com/nim-works/nimskull/pull/932, except that one may encounter `checkMinSonsLen`, `checkMinSonsLen` report global error prevent downstream errors, this one calls `semReportIllformedAst` which internally call `handleReport` directly, instead of `globalReport` or `localReport`, so the error affect rest part of procedure and downstream.

2023-10-01 16:20 UTC, zerbina commented
> internally call `handleReport` directly, instead of `globalReport` or `localReport`, so the error affect rest part of procedure and downstream

`localReport` also only calls `handleReport` with `doNothing`, which is the same thing that `semReportIllformedAst` does. A `globalReport` would have indeed prevented the crash, as it raises an `ERecoverableError`.

In general, the direction is that all calls to `globalReport`, `localReport`, `handleReport`, etc. should be replaced with `nkError` propagation, so that progress can be made despite ill-formed/illegal code. Turning all the `checkSonsLen`, etc. into `nkError` propagation would be quite the effort, however -- #508 was/is intended to help there.

2023-10-01 16:21 UTC, zerbina approved these changes

2023-10-01 16:21 UTC, zerbina commented
/merge

2023-10-01 16:58 UTC, merged