fix `hasCom` miss case by replacing `nkEmpty..nkNilLit` to `nkWithoutSons`
nim-works/nimskull pull request #937
Opened 2023-10-02 18:20 UTC by bung87

## Summary
* fix `hasCom` miss case by replacing `nkEmpty..nkNilLit` to `nkWithoutSons`
* prevent it goes to `else` branch iterate child nodes cause `FieldDefect`

## Details
* the `nkWithoutSons` includes extro `nkNone`, `nkError` than before.

---

## Notes for Reviewers

<!--
Pull Request(PR) Help

Before Merge Ensure:
* title reads like a short changelog line entry
* code includes tests and is documented
* leave the source better than before, but split out big reformats

See contributor (guide)[https://nim-works.github.io/nimskull/contributing.html]
for details, especially if you're new to this project.

Tips that make PRs easier:
* for big/impactful changes, start with chat/discussions to refine ideas
* refine the pull request message over time; don't have to nail it in one go

2023-10-02 20:00 UTC, saem requested changes
A few things:

- the change needs a test case
- pr body should include a description of what was failing before

2023-10-03 04:56 UTC, bung87 commented
* the problem is obvious to me
* said cause `FieldDefect`

2023-10-03 21:57 UTC, saem commented on compiler/ast/renderer.nim
>    else:
```suggestion
  of nkWithSons:
```

making it exhaustive will reduce the chance of missed branches.

2023-10-03 22:08 UTC, saem commented
There is the exhausitiveness suggestion, otherwise this is good to go.

PS. I've updated the PR description, assuming the exhaustiveness change goes through.

2023-10-04 15:18 UTC, saem approved these changes

2023-10-04 15:18 UTC, saem commented
/merge

2023-10-04 15:52 UTC, merged