fix `parentModule` returns `0` cause compile `config/nim.cfg`
nim-works/nimskull pull request #953
Opened 2023-10-11 09:31 UTC by bung87

## Summary
* what changed and how?
* why are we changing it?

## Details
* info that couldn't fit into the summary
* relevant details; tricky parts
* anything else

Fixes full_issue_url

---

## Notes for Reviewers
* leave additional context for reviewers
* maybe specific requests or areas of focus

<!--
Pull Request(PR) Help

Before Merge Ensure:
* title reads like a short changelog line entry
* code includes tests and is documented
* leave the source better than before, but split out big reformats

See contributor (guide)[https://nim-works.github.io/nimskull/contributing.html]
for details, especially if you're new to this project.

Tips that make PRs easier:
* for big/impactful changes, start with chat/discussions to refine ideas
* refine the pull request message over time; don't have to nail it in one go

2023-10-11 17:30 UTC, saem requested changes
Please add a test.

2023-10-12 07:02 UTC, bung87 commented
I debuged this locally and test it through LSP, the isolated module `compiler/vm/compilerbridge.nim` initialized with project file `vm.nim` , then the `parentModule` procedure assuming given module whether indexed with project file via import or include, no, it does't, and the issue can be evidenced without this context, inside the `parentModule` procedure `else` branch `getOrDefault` default to `0` .

2023-10-12 18:45 UTC, saem commented
I don't see how it could fail outside of a suggest context, because that'd be the only time we'd get a module outside the project + transitive closure of dependent modules. Am I missing something?

There are similar tests already in `nimsuggest/tests` adding another one doesn't seem like a big deal, unless there is a simpler way to test it.

2023-10-13 07:41 UTC, bung87 commented
as said it's _isolated_, a file belongs to a project in directory structure doesn't proven it been indexed in project's `graph`

2023-10-13 15:19 UTC, saem commented
That's only half the condition, the file has to be queried for in order to actually trigger things.

Regardless, it still needs a test, this would have easily been caught with a test initially and prevented any regression.

2023-10-17 19:21 UTC, saem commented on nimsuggest/tests/tisolated.nim
> +# 2. a file that used by explicitly importing in another project.
I updated the phrasing, I'm pretty sure I got the meaning right.

```suggestion
# Regression test for querying a file/module that is not the project file/module
# or part of the transitive closure of all dependencies (via import or include).
# In such a case the queried file is not indexed within the project's graph.
#
# Covered use cases:
# 1. a new file under project directory structure not imported nor included by
#    compiled files.
# 2. a file that's used by explicitly importing in another project.
```

Regression test looks good.

2023-10-17 19:33 UTC, saem commented
I've updated the PR body, just waiting to resolve the documentation update.

2023-10-17 19:34 UTC, saem requested changes
Suggested some grammar fixes, if they're good to go, then I can merge this PR once they're in.

2023-10-18 23:07 UTC, saem approved these changes

2023-10-18 23:07 UTC, saem commented
/merge

2023-10-19 00:08 UTC, merged